added fishhook mode in arrow tool

diff --git a/data/compile_rc b/data/compile_rc
--- a/data/compile_rc
+++ b/data/compile_rc
@@ -1,3 +1,21 @@
 #!/bin/bash
 
-pyrcc5 -o ../chemcanvas/resources_rc.py resources.qrc
+echo "<RCC>" > _resources.qrc
+echo "  <qresource>" >> _resources.qrc
+
+for f in icons/*; do
+    echo "    <file>${f}</file>" >> _resources.qrc
+done
+
+echo "  </qresource>" >> _resources.qrc
+echo "</RCC>" >> _resources.qrc
+
+pyrcc5 -o ../chemcanvas/resources_rc.py _resources.qrc
+
+if [ $? -eq 0 ]; then
+    echo "Compiled Resources saved as ../chemcanvas/resources_rc.py"
+else
+    echo "Failed to compile resources"
+fi
+
+rm _resources.qrc
